// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpsnmojodjattkltjnbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwc25tb2pvZGphdHRrbHRqbmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTQyNzksImV4cCI6MjA2MDgzMDI3OX0.Ca9KXFT0oSh6C1lb1-O2zgnENlmCYe_WLzKEv6h0d2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);